name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip
      - run: pip install -e .[nlp] pytest
      - run: pytest -q
      - name: Report smoke
        run: |
          echo '“x”—y\u200B' | cleanup-text --report --json | python - <<'PY'
          import sys, json
          data=json.load(sys.stdin)
          assert "-" in data and data["-"]["total"]>=1
          PY